services:
  filebrowser:
    image: hurlenko/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    user: '65534:65534' # nobody user for compatibility with WordPress container
    ports:
      - 127.0.0.1:6900:8080
    networks:
      - coolify
    volumes:
      - /home/spires/sites:/data
      - ./filebrowser/config:/config
    environment:
      - FB_BASEURL=/
    # Uncomment and adjust Caddy labels if needed
    # labels:
    #   caddy: files.example.com
    #   caddy.0_import: crowdsec
    #   caddy.2_tls: internal
    #   caddy.3_reverse_proxy: "{{upstreams 8080}}"
    #   caddy.3_reverse_proxy.0_header_up: X-Real-IP {client_ip}
    #   caddy.3_reverse_proxy.1_header_up: X-Forwarded-For {client_ip}

  watchtower:
    image: beatkind/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true
    networks:
      - coolify # Add watchtower to the same network for consistency

# Define the coolify network
networks:
  coolify:
    driver: bridge
